### ISSUE TITLE
Error: unable to verify the first certificate

### ISSUE THREAD

**Issue by ejj28** [tidepool-org/animas-diasend-data#4]
When running `node ./download-diasend -u "USER" -p "PASSWORD" out.xls` I get this error: 

>Downloading USER's Animas xls to include 14 days of data.
Saving xls in out.xls
internal/streams/legacy.js:59
      throw er; // Unhandled stream error in pipe.
      ^
Error: unable to verify the first certificate
    at TLSSocket.<anonymous> (_tls_wrap.js:1098:38)
    at emitNone (events.js:105:13)
    at TLSSocket.emit (events.js:207:7)
    at TLSSocket._finishInit (_tls_wrap.js:628:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:458:38)

**Comment by ejj28** [comment]
After figuring out a workaround that I don't remember, I realized that this script no longer works. The page it tries to get data from is no longer available.
